# Generated by Django 4.2.11 on 2025-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='photo_reference',
            field=models.ImageField(blank=True, help_text='Photo de format 4x4 (carré) pour la reconnaissance faciale', null=True, upload_to='photos_eleves/'),
        ),
        migrations.AlterField(
            model_name='sessionappel',
            name='methode',
            field=models.CharField(choices=[('FACIAL', 'Reconnaissance faciale'), ('QR_CODE', 'Scan QR Code'), ('MANUEL', 'Manuel'), ('MIXTE', 'Mixte')], default='QR_CODE', max_length=20),
        ),
    ]
