# Generated by Django 4.2.11 on 2025-09-27 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_eleve_photo_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.CharField(choices=[('PREMIER', 'First cycle (6th → 3rd)'), ('SECOND', 'Second cycle (10th → 12th)')], default='PREMIER', max_length=10),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(choices=[('6A', '6th A'), ('6B', '6th B'), ('5A', '5th A'), ('5B', '5th B'), ('4A', '4th A'), ('4B', '4th B'), ('3A', '3rd A'), ('3B', '3rd B'), ('2ND', '10th'), ('1ERE', '11th'), ('TLE', '12th')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cours',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Scheduled'), ('EN_COURS', 'In Progress'), ('TERMINE', 'Completed'), ('ANNULE', 'Cancelled')], default='PLANIFIE', max_length=20),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='photo_reference',
            field=models.ImageField(blank=True, help_text='4x4 square photo for facial recognition', null=True, upload_to='photos_eleves/'),
        ),
        migrations.AlterField(
            model_name='historiquepresence',
            name='methode_detection',
            field=models.CharField(choices=[('FACIAL', 'Facial Recognition'), ('MANUEL', 'Manual'), ('QR_CODE', 'QR Code')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historiquepresence',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('RETARD', 'Late'), ('JUSTIFIE', 'Justified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('ABSENCE', 'Absence'), ('RETARD', 'Late'), ('PRESENCE', 'Attendance'), ('SYSTEME', 'System')], max_length=20),
        ),
        migrations.AlterField(
            model_name='presence',
            name='methode_detection',
            field=models.CharField(choices=[('FACIAL', 'Facial Recognition'), ('MANUEL', 'Manual'), ('QR_CODE', 'QR Code')], default='MANUEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('RETARD', 'Late'), ('JUSTIFIE', 'Justified')], default='ABSENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionappel',
            name='methode',
            field=models.CharField(choices=[('FACIAL', 'Facial Recognition'), ('QR_CODE', 'QR Code Scan'), ('MANUEL', 'Manual'), ('MIXTE', 'Mixed')], default='QR_CODE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionappel',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'In Progress'), ('TERMINE', 'Completed'), ('ANNULE', 'Cancelled')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ENSEIGNANT', 'Teacher'), ('ELEVE', 'Student'), ('PARENT', 'Parent')], default='ELEVE', max_length=20),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_feedback', models.CharField(choices=[('GENERAL', 'General Question'), ('ABSENCE', 'Absence Justification'), ('RETARD', 'Delay Explanation'), ('COMPORTEMENT', 'Behavior Concern'), ('ACADEMIQUE', 'Academic Question'), ('TECHNIQUE', 'Technical Issue'), ('AUTRE', 'Other')], default='GENERAL', max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVEAU', 'New'), ('EN_COURS', 'In Progress'), ('REPONDU', 'Answered'), ('FERME', 'Closed')], default='NOUVEAU', max_length=20)),
                ('priorite', models.CharField(choices=[('FAIBLE', 'Low'), ('NORMALE', 'Normal'), ('HAUTE', 'High'), ('URGENTE', 'Urgent')], default='NORMALE', max_length=10)),
                ('reponse', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.cours')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.eleve')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.parent')),
                ('reponse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_repondus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
