# Generated by Django 4.2.11 on 2025-10-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_classe_cycle_alter_classe_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.CharField(choices=[('PREMIER', 'First cycle (Form 1 → Form 5)'), ('SECOND', 'Second cycle (Lower → Upper)')], default='PREMIER', max_length=10),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(choices=[('Form1_A', 'Form 1A'), ('Form1_B', 'Form 1B'), ('Form2_A', 'Form 2A'), ('Form2_B', 'Form 2A'), ('Form3_A', 'Form 3A'), ('Form3_B', 'Form 3B'), ('Form4_A', '3rd A'), ('Form4_B', 'Form 4B'), ('Form5_A', 'Form 5A'), ('Lower_Sixth', 'Lower Sixth'), ('Upper_Sixth', 'Upper_Sixth')], max_length=20),
        ),
    ]
